//! Golden parity suite: the correctness anchor for the whole rewrite (issue 08).
//!
//! Each fixture under `tests/golden/` is a real historical match — migrated
//! from the predecessor app's SQLite database to a version-1 Match File — paired
//! with that Python app's derived statistics, captured while the old app still
//! ran. This suite imports every Match File through the same [`MatchFile`] path
//! the app uses, re-derives its statistics with [`derive_stats`], and asserts
//! the result reproduces the Python oracle exactly — save for a small ledger of
//! deliberate, documented deviations.
//!
//! Where the Rust engine and the Python oracle legitimately disagree — always
//! because CentrePass derives possession boundaries from the log rather than
//! honouring the predecessor's coded `RESET` sentinels (ADR-0003) — the
//! difference is recorded in `tests/golden/deviations.json`, with its rationale
//! in `tests/golden/DEVIATIONS.md`. The ledger is self-checking: an
//! *undocumented* difference fails the suite (a real regression), and a *stale*
//! deviation that no longer applies fails it too. Never regenerate a fixture to
//! make a test pass.
//!
//! Fixtures and the oracle projection are generated by
//! `scripts/gen_golden_fixtures.py` in the predecessor repo
//! (louispt1/Netballstats); they are committed here so the suite runs in CI
//! with no external dependency.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use netball_core::{derive_stats, MatchFile, StatsReport, Team, TeamStats};
use serde::{Deserialize, Serialize};
use serde_json::Value;

// ── The canonical parity projection ──────────────────────────────────────────

/// The engine-agnostic projection of a match's statistics that both the Rust
/// engine and the Python oracle produce. Playing time and rendered percentages
/// are intentionally excluded (see `DEVIATIONS.md`).
#[derive(Debug, Serialize, Deserialize)]
struct Golden {
    score: ScorePair,
    teams: Teams,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct ScorePair {
    team_a: u32,
    team_b: u32,
}

#[derive(Debug, Serialize, Deserialize)]
struct Teams {
    #[serde(rename = "A")]
    a: TeamProjection,
    #[serde(rename = "B")]
    b: TeamProjection,
}

#[derive(Debug, Serialize, Deserialize)]
struct TeamProjection {
    /// Per-player counts, keyed by player name (a `BTreeMap` so the comparison
    /// is order-independent: the engine lists players in appearance order, the
    /// oracle has no inherent order).
    players: BTreeMap<String, PlayerProjection>,
    totals: Totals,
    conversions: Conversions,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct PlayerProjection {
    goals: u32,
    shots: u32,
    feeds: u32,
    completed_feeds: u32,
    attacking_rebounds: u32,
    defensive_rebounds: u32,
    unforced_turnovers: u32,
    gains: u32,
}

/// Team-level figures the oracle reports only in aggregate; the engine's
/// per-player equivalents are summed to compare.
#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Totals {
    feeds_with_shot: u32,
    goal_assists: u32,
    infringements: u32,
}

#[derive(Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Conversions {
    centre_pass_total: u32,
    centre_pass_goals: u32,
    gain_total: u32,
    gain_goals: u32,
}

impl Golden {
    /// Project a derived [`StatsReport`] into the canonical parity shape.
    fn from_report(report: &StatsReport) -> Golden {
        Golden {
            score: ScorePair {
                team_a: report.score.team_a,
                team_b: report.score.team_b,
            },
            teams: Teams {
                a: TeamProjection::from_team(team_stats(report, Team::A)),
                b: TeamProjection::from_team(team_stats(report, Team::B)),
            },
        }
    }
}

impl TeamProjection {
    fn from_team(team: &TeamStats) -> TeamProjection {
        let players = team
            .players
            .iter()
            .map(|p| {
                (
                    p.player.clone(),
                    PlayerProjection {
                        goals: p.goals,
                        shots: p.shots,
                        feeds: p.feeds,
                        completed_feeds: p.completed_feeds,
                        attacking_rebounds: p.attacking_rebounds,
                        defensive_rebounds: p.defensive_rebounds,
                        unforced_turnovers: p.unforced_turnovers,
                        gains: p.gains,
                    },
                )
            })
            .collect();
        TeamProjection {
            players,
            totals: Totals {
                feeds_with_shot: team.players.iter().map(|p| p.feeds_with_shot).sum(),
                goal_assists: team.players.iter().map(|p| p.goal_assists).sum(),
                infringements: team.players.iter().map(|p| p.infringements).sum(),
            },
            conversions: Conversions {
                centre_pass_total: team.conversions.centre_pass_total,
                centre_pass_goals: team.conversions.centre_pass_goals,
                gain_total: team.conversions.gain_total,
                gain_goals: team.conversions.gain_goals,
            },
        }
    }
}

fn team_stats(report: &StatsReport, team: Team) -> &TeamStats {
    report
        .teams
        .iter()
        .find(|t| t.team == team)
        .expect("report always carries both teams")
}

// ── The deviation ledger ─────────────────────────────────────────────────────

/// One documented, deliberate difference between the engine and the oracle, at
/// a single leaf of the canonical projection.
#[derive(Debug, Clone, Deserialize)]
struct Deviation {
    fixture: String,
    /// Dotted path into the projection, e.g. `teams.B.conversions.gainTotal`.
    path: String,
    /// The Python oracle's value at that path.
    oracle: Value,
    /// The value the engine is expected to produce instead.
    engine: Value,
    /// Rationale key, cross-referenced in `DEVIATIONS.md`.
    #[allow(dead_code)]
    reason: String,
}

/// A single leaf difference discovered by walking two projections.
#[derive(Debug)]
struct Diff {
    path: String,
    engine: Value,
    oracle: Value,
}

/// Collect every scalar-leaf difference between the engine projection and the
/// oracle, as dotted paths. Object keys present in only one side surface as a
/// difference against `null`, so a missing or extra player never hides.
fn diff_values(engine: &Value, oracle: &Value, path: &str, out: &mut Vec<Diff>) {
    match (engine, oracle) {
        (Value::Object(e), Value::Object(o)) => {
            let mut keys: Vec<&String> = e.keys().chain(o.keys()).collect();
            keys.sort();
            keys.dedup();
            for key in keys {
                let child = if path.is_empty() {
                    key.clone()
                } else {
                    format!("{path}.{key}")
                };
                let null = Value::Null;
                diff_values(
                    e.get(key).unwrap_or(&null),
                    o.get(key).unwrap_or(&null),
                    &child,
                    out,
                );
            }
        }
        _ => {
            if engine != oracle {
                out.push(Diff {
                    path: path.to_string(),
                    engine: engine.clone(),
                    oracle: oracle.clone(),
                });
            }
        }
    }
}

// ── Fixtures ─────────────────────────────────────────────────────────────────

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden")
}

/// Every fixture's stable name (its `*.matchfile.json` basename), sorted.
fn fixture_names() -> Vec<String> {
    let mut names: Vec<String> = fs::read_dir(golden_dir())
        .expect("golden fixture directory exists")
        .filter_map(|entry| {
            let name = entry.ok()?.file_name().into_string().ok()?;
            name.strip_suffix(".matchfile.json").map(str::to_string)
        })
        .collect();
    names.sort();
    names
}

fn load_deviations() -> Vec<Deviation> {
    let path = golden_dir().join("deviations.json");
    let json = fs::read_to_string(&path).expect("deviations.json exists (may be an empty [])");
    serde_json::from_str(&json).expect("deviations.json is well-formed")
}

#[test]
fn at_least_five_real_fixtures_are_present() {
    // The acceptance criterion: a fixture set of at least five real matches.
    // (The synthetic substitution fixture is additional coverage, not counted.)
    let real = fixture_names()
        .iter()
        .filter(|n| !n.contains("synthetic"))
        .count();
    assert!(
        real >= 5,
        "expected at least five real fixtures, found {real}"
    );
}

#[test]
fn every_fixture_reproduces_the_python_oracle_modulo_documented_deviations() {
    let names = fixture_names();
    assert!(!names.is_empty(), "no golden fixtures found");
    let deviations = load_deviations();
    let mut used = vec![false; deviations.len()];
    let mut failures: Vec<String> = Vec::new();

    for name in &names {
        // Importing through MatchFile::from_json is the same path the app's
        // import flow uses: a clean parse proves the migrated file imports.
        let match_json = fs::read_to_string(golden_dir().join(format!("{name}.matchfile.json")))
            .expect("read match file");
        let match_file = match MatchFile::from_json(&match_json) {
            Ok(mf) => mf,
            Err(e) => {
                failures.push(format!("{name}: failed to import: {e}"));
                continue;
            }
        };

        let expected_json = fs::read_to_string(golden_dir().join(format!("{name}.expected.json")))
            .unwrap_or_else(|_| panic!("fixture {name} is missing its .expected.json"));
        let oracle: Golden = serde_json::from_str(&expected_json)
            .unwrap_or_else(|e| panic!("fixture {name} has malformed expected stats: {e}"));

        let engine = Golden::from_report(&derive_stats(&match_file.log));
        let engine_value = serde_json::to_value(&engine).unwrap();
        let oracle_value = serde_json::to_value(&oracle).unwrap();

        let mut diffs = Vec::new();
        diff_values(&engine_value, &oracle_value, "", &mut diffs);

        for diff in diffs {
            // A difference is allowed only if the ledger documents exactly it:
            // same fixture, same path, same oracle value, and the engine value
            // the engine is expected to produce.
            let matched = deviations.iter().enumerate().find(|(_, d)| {
                d.fixture == *name
                    && d.path == diff.path
                    && d.oracle == diff.oracle
                    && d.engine == diff.engine
            });
            match matched {
                Some((i, _)) => used[i] = true,
                None => failures.push(format!(
                    "{name}: undocumented parity break at {} — engine {} vs oracle {}. \
                     Fix the engine, or record it in deviations.json + DEVIATIONS.md.",
                    diff.path, diff.engine, diff.oracle
                )),
            }
        }
    }

    // A deviation for a present fixture that never fired is stale: either the
    // engine changed or the fixture did, and the ledger must be pruned.
    for (i, deviation) in deviations.iter().enumerate() {
        if !used[i] && names.contains(&deviation.fixture) {
            failures.push(format!(
                "stale deviation: {} at {} no longer applies — remove it from deviations.json",
                deviation.fixture, deviation.path
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "golden parity failures:\n  {}",
        failures.join("\n  ")
    );
}
